config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
             controller: "clearance/passwords",
             only: [:create, :edit, :update]
  end

  resource :chart, only: [:new, :create, :edit, :update]
  resource :dashboard, only: :show
  resources :submissions, only: [:new, :create]

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  root 'welcome#index'
end

app/models/chart.rb
class Chart < ActiveRecord::Base
  belongs_to :user
  has_many :items
  has_many :submissions, -> { order(:date) }

  accepts_nested_attributes_for :items

  def item_names
    items.map(&:name)
  end

  def submission_pending?
    submissions.pending?
  end
end

app/models/dashboard.rb
class Dashboard
  attr_reader :chart, :stats
  delegate :submission_pending?, to: :chart

  def initialize(chart)
    @chart = chart
    @stats = DailyChart.generate_stats(chart: chart)
  end

  def last_seven_days
    stats.daily.map(&:first)
  end

  def daily_percentages
    stats.daily.map(&:second)
  end

  def weekly_percentages
    stats.weekly
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :chart
end

app/models/no_submission.rb
class NoSubmission
  include DateFormatters
  attr_reader :date

  def initialize(date)
    @date = date
  end

  def score
    0
  end

  def percent
    0.0
  end

  def data
    {}
  end
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  include DateFormatters
  belongs_to :chart
  has_many :submission_details

  validates :date, uniqueness: true, presence: true

  before_validation :set_date
  before_save :set_score

  def self.pending?
    find_by(date: Time.zone.today).nil?
  end

  def percent
    return 0.0 if max_score.zero?
    (score.to_f / max_score * 100.0).round(2)
  end

  private

  def set_score
    self.score = submission_details.count(&:checked?)
  end

  def set_date
    self.date ||= Time.zone.today
  end

  def max_score
    submission_details.count
  end
end

app/models/submission_detail.rb
class SubmissionDetail < ActiveRecord::Base
  belongs_to :chart
  belongs_to :item
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  has_one :chart
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_chart
    current_user.chart
  end
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  before_action :require_login

  def new
    if current_chart
      flash[:alert] = "You already have a chart"
      redirect_to dashboard_path
    else
      @chart = Chart.new
      @chart.items.build
    end
  end

  def create
    @chart = current_user.build_chart(chart_params)
    if @chart.save
      flash[:notice] = "Created new chart"
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def edit
    @chart = current_chart
  end

  def update
    @chart = current_chart
    @chart.items.clear
    if @chart.update(chart_params)
      flash[:notice] = "Edited chart"
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  private

  def chart_params
    params.require(:chart).permit(items_attributes: [:name])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :require_login, :require_chart

  def show
    @dashboard = Dashboard.new(current_chart)
  end

  private

  def require_chart
    redirect_to new_chart_path unless current_chart
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :require_login

  def new
    @chart = current_chart
  end

  def create
    submission = DailyChart.build_submission(
      chart: current_chart,
      data: submission_params.to_h.transform_values { |v| v == "1" }
    )

    if submission.save
      flash[:notice] = "Chart submitted for #{Time.zone.today}"
    else
      flash[:alert] = "Chart already submitted for #{Time.zone.today}"
    end
    redirect_to dashboard_path
  end

  private

  def submission_params
    params.require(:submission).permit(current_item_names)
  end

  def current_item_names
    current_chart.items.map(&:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if signed_in?
      if current_chart
        redirect_to dashboard_path
      else
        redirect_to new_chart_path
      end
    else
      redirect_to sign_up_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/charts/_form.html.erb
<%= form_for @chart, url: chart_path do |f| %>
  <div id="items">
    <%= f.fields_for :items do |ff| %>
      <div class="item" id="item_<%= ff.index %>">
        <%= ff.label "#{ff.index + 1}" %>
        <%= ff.text_field :name %>
        <button type="button" class="removeItem" id="remove_item_<%= ff.index %>">
          <span class="glyphicon glyphicon-remove"></span>
        </button>
      </div>
    <% end %>
  </div>
  <div>
    <button type="button" class="btn btn-default" id="addItem">Add an item</button>
    <%= f.submit "Submit", class: "btn btn-submit" %>
  </div>
<% end %>

app/views/charts/edit.html.erb
<%= render "form" %>

app/views/charts/new.html.erb
<button id="addItem">Add an item</button>

<%= form_for @chart, url: chart_path do |f| %>
  <div id="items">
    <%= f.fields_for :items do |ff| %>
      <div class="item">
        <%= ff.label :name %>
        <%= ff.text_field :name %>
      </div>
    <% end %>
  </div>
  <div>
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/dashboards/show.html.erb
<% if @dashboard.submission_pending? %>
  <%= link_to "Submit today's chart", new_submission_path %>
<% end %>

<div class="container">
  <div class="row">
    <div id="weeklyScores"></div>
  </div>
  </br>
  <div class="row">
    <div id="allTimeScores"></div>
  </div>
</div>

<script>
 $(function () {
   $("#weeklyScores").highcharts({
     chart: {
       type: "spline"
     },
     title: {
       text: "Weekly Scores",
       x: -20 //center
     },
     legend: {
       enabled: false
     },
     xAxis: {
       categories: <%= @dashboard.last_seven_days.to_s.html_safe %>,
       title: {
         text: "Day"
       }
     },
     yAxis: {
       title: {
         text: "Percent (%)"
       },
       plotLines: [{
         value: 0,
         width: 1,
         color: '#808080'
       }]
     },
     tooltip: {
       valueSuffix: "%"
     },
     plotOptions: {
       spline: {
         lineWidth: 4,
         marker: {
           enabled: false
         }
       }
     },
     series: [{
       name: 'Score',
       data: <%= @dashboard.daily_percentages %>
     }]
   });
 });

 $(function () {
   $("#allTimeScores").highcharts({
     chart: {
       type: "area"
     },
     title: {
       text: "All Time",
       x: -20 //center
     },
     legend: {
       enabled: false
     },
     xAxis: {
       categories: <%= 1.upto(@dashboard.weekly_percentages.size).to_a.to_s.html_safe %>,
       title: {
         text: "Week no."
       }
     },
     yAxis: {
       title: {
         text: "Percent (%)"
       },
       plotLines: [{
         value: 0,
         width: 1,
         color: '#808080'
       }]
     },
     tooltip: {
       valueSuffix: "%"
     },
     plotOptions: {
       series: {
         stacking: "normal"
       }
     },
     series: [
       <% @dashboard.weekly_percentages.each do |name, data| %>
       {
         name: "<%= name %>",
         data: <%= data %>
       },
       <% end %>
     ]
   });
 });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag "https://code.highcharts.com/highcharts.js" %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div class="navbar navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-inner">
        <%= link_to "Daily Chart", root_path, class: "navbar-brand" %>
        <ul class="nav navbar-nav">
          <li><%= link_to "Edit", edit_chart_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <% if signed_in? -%>
              <%= link_to t(".sign_out"), sign_out_path, method: :delete %>
            <% else -%>
              <%= link_to t(".sign_in"), sign_in_path %>
            <% end -%>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <div class="container">
    <div id="flash">
      <% flash.each do |key, value| -%>
        <div id="flash_<%= key %>" class="<%= key %>"><%=h value %></div>
      <% end %>
    </div>

    <%= yield %>
  </div>
</body>
</html>

app/views/submissions/new.html.erb
<%= form_for :submission, url: submissions_path, class: "form-horizontal" do |f| %>
  <% @chart.items.each do |item| %>
    <div class="form-group">
      <%= f.check_box item.name %>
      <%= f.label item.name %>
    </div>
  <% end %>

  <div class="form-group"><%= f.submit "Submit", class: "btn btn-submit" %></div>
<% end %>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/create.html.erb
<h1>Account was successfully created</h1>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>